env:
  - BRANCH=development

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/nim-$BRANCH/bin:$PATH"
  - export NIM_LIB_PREFIX=$TRAVIS_BUILD_DIR/nim-$BRANCH/

install:
  - bash ./scripts/install.sh

script: 
  - nim c -d:release csv.nim
  - bash functional-tests.sh